---
- name: Check installed Helm version
  ansible.builtin.command: helm version --template {% raw %}'{{ .Version }}'{% endraw %}
  register: helm_installed
  changed_when: false
  failed_when: false

- name: Install Helm
  when: helm_installed.rc != 0 or helm_installed.stdout != helm_version
  block:
    - name: Download Helm archive
      ansible.builtin.get_url:
        url: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
        checksum: "sha256:https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz.sha256sum"
        dest: "/tmp/helm-{{ helm_version }}.tar.gz"
        mode: "0644"

    - name: Unpack Helm binary
      ansible.builtin.unarchive:
        src: "/tmp/helm-{{ helm_version }}.tar.gz"
        dest: /usr/local/bin
        remote_src: true
        extra_opts: [--strip-components=1, linux-amd64/helm]
