apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

labels:
  - pairs:
      app.kubernetes.io/part-of: devops-case
    includeSelectors: false

resources:
  - daemonset.yaml

# Хэш в имени ConfigMap: изменение fluent.conf само перезапускает Fluentd
configMapGenerator:
  - name: fluentd
    files:
      - fluent.conf
