apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo

labels:
  - pairs:
      app.kubernetes.io/part-of: devops-case
    includeSelectors: false

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - servicemonitor.yaml

# Хэш в имени ConfigMap: изменение nginx.conf само перезапускает поды
configMapGenerator:
  - name: hello-nginx
    files:
      - nginx.conf
